---
SimpleDB:
  Domain: multifamily-properties
LoopNet:
  pageguid: 5e5a9e35-c426-48f8-8448-2eb8a8140262
  criteria:
    AgentFirstName: 
    AgentLastName: 
    ApartmentStyleTypes: 0
    Auction: true
    AuctionAssetTypeNotes: 
    AuctionAssetTypeProperties: 
    AuctionFinanceTypeBrokerCoOp: 
    AuctionFinanceTypeFinancing: 
    AuctionIds: 
    AvailableForLease: true
    BoundsChangedViaMapInteraction: false
    BuildingClass: 0
    BuildingParkFilter: 0
    BuildingSizeRangeMax: 
    BuildingSizeRangeMin: 
    BuildingSizeUom: SquareFeet
    BusinessForSale: true
    CapRateRangeMax: 
    CapRateRangeMin: 
    City: Indianapolis
    CondosFilter: 0
    Country: US
    Currency: 
    DateEnteredRangeMax: 
    DateEnteredRangeMin: 
    DateEnteredType: RT
    DateFormat: MM/dd/yyyy
    DateIndicator: 0
    Distance: 0
    Distressed: false
    Editor: Universal
    FlexSubtypes: 0
    ForceRemoveBoundary: false
    GeneralRetailSubtypes: 0
    GeographyFilters: 
    - BoundingBox: 
      - -86.3750002
      - 39.600893
      - -85.9331999
      - 39.95669
      Centroid: 
      - -86.15410005
      - 39.7787915
      Code:  IN
      Display: Indianapolis
      GeographyId: 16284
      GeographyType: 2
      MatchType: 3
      Radius: 0
      RadiusLengthMeasure: 0
      SubmarketPropertyType: 0
      TypeaheadDisplay: Indianapolis IN USA
    HasMultipleLocations: false
    HasValidCoordinates: 
    HealthcareSubtypes: 0
    HospitalitySubtypes: 0
    IncludeProximityCities: false
    InContract: true
    IndustrialSubtypes: 0
    InOpportunityZone: 
    Investment: true
    InvestmentTypeCore: 
    InvestmentTypeOpportunistic: 
    InvestmentTypeOpportunityZone: 
    InvestmentTypeTripleNet: 
    InvestmentTypeValueAdd: 
    IsAuctionsOnly: false
    IsDefaultLeaseRate: true
    IsForLease: false
    IsForSale: true
    IsTenXAuctions: false
    IsUserFromUS: true
    Keywords: 
    LandTypes: 0
    LeaseRateCurrency: USD
    LeaseRatePerSizeUom: SquareFeet
    LeaseRateRangeMax: 
    LeaseRateRangeMin: 
    LeaseRateTerm: y
    LeaseRateUomTerm: SquareFeetYearForUI
    ListingId: 
    ListingIdPinClick: 
    ListingSearchType: 1
    ListingType: 2
    LNPropertyTypes: 512
    LoopLinkForLeaseDefaultSorting: []
    LoopLinkForSaleAndLeaseDefaultSorting: []
    LoopLinkForSaleDefaultSorting: []
    LotSizeRangeMax: 
    LotSizeRangeMin: 
    LotSizeUom: Acres
    Market: 
    MinimumDate: 01/01/0001
    MoveInDateEnteredRangeMax: 
    MoveInDateEnteredRangeMin: 
    MoveInDateEnteredType: 
    MoveInDateIndicator: 0
    MSA: 
    MultifamilySubtypes: 0
    Multiple: false
    NetLeased: false
    OfficeSubtypes: 0
    OnMarketDateRange: 
    Origin: 1
    PageLocationLabel: Indianapolis IN
    PageNumber: 1
    PageSize: 500
    PendingForLease: false
    PercentMajorityCountryCode: US
    Polygon: 
    PortfoliosFilter: 0
    PreserveAddressForRadiusSavedSearch: false
    PriceRangeCurrency: USD
    PriceRangeMax: 
    PriceRangeMin: 
    PriceRangeRateType: Total
    PropertyTypes: 0
    Radius: 
    Region: 
    RegionalMarket: 
    ResultLimit: 500
    ShoppingCenterFilter: 0
    ShoppingCenterTypes: 0
    Single: false
    SpaceAvailableRangeMax: 
    SpaceAvailableRangeMin: 
    SpaceAvailableUom: SquareFeet
    SpaceLeaseTypes: 0
    SpecialtySubtypes: 0
    SportsAndEntertainmentSubtypes: 0
    State: IN
    StateKey: af8ce762266edb4fe2f2fb0ec1df374b
    SubCategoryList: []
    SubLease: false
    SubMarket: 
    TermLengthRangeMax: 
    TermLengthRangeMin: 
    Timeout: 0
    TypeaheadLocationLabel: Indianapolis IN USA
    UnitCountRangeMax: 
    UnitCountRangeMin: 
    UseClassTypes: 0
    VacantOwner: true
    ViewMode: None
    YearBuiltRangeMax: 
    YearBuiltRangeMin: 